"use client";

import React, { useState } from 'react';
import { robots } from './registry';
import { ChevronLeft, ChevronRight, Github } from 'lucide-react';
import Link from 'next/link';

export default function RobotPage() {
    const [currentIndex, setCurrentIndex] = useState(0);
    const currentRobot = robots[currentIndex];

    const nextRobot = () => {
        setCurrentIndex((prev) => (prev + 1) % robots.length);
    };

    const prevRobot = () => {
        setCurrentIndex((prev) => (prev - 1 + robots.length) % robots.length);
    };

    return (
        <div className="flex flex-col items-center justify-center min-h-[calc(100vh-8rem)] p-4 relative">
            <h1 className="text-4xl md:text-6xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-primary to-accent font-orbitron mb-2 animate-pulse text-center">
                {currentRobot.name}
            </h1>

            <p className="text-lg md:text-xl text-gray-400 font-mono mb-8 flex items-center gap-2">
                GENERATED BY: <span className="text-primary font-bold">{currentRobot.model}</span>
            </p>

            <div className="w-full max-w-2xl aspect-square relative group">
                <div className="absolute inset-0 bg-gradient-to-b from-primary/10 to-transparent rounded-full blur-3xl -z-10" />

                {/* Robot Display */}
                <div className="w-full h-full p-4 transition-all duration-500 ease-in-out">
                    <currentRobot.component className="drop-shadow-[0_0_30px_rgba(0,255,255,0.3)]" />
                </div>

                {/* Navigation (Only show if multiple robots) */}
                {robots.length > 1 && (
                    <>
                        <button
                            onClick={prevRobot}
                            className="absolute left-0 top-1/2 -translate-y-1/2 p-2 rounded-full bg-black/50 text-white hover:bg-primary/50 transition-colors backdrop-blur-sm"
                        >
                            <ChevronLeft size={32} />
                        </button>
                        <button
                            onClick={nextRobot}
                            className="absolute right-0 top-1/2 -translate-y-1/2 p-2 rounded-full bg-black/50 text-white hover:bg-primary/50 transition-colors backdrop-blur-sm"
                        >
                            <ChevronRight size={32} />
                        </button>
                    </>
                )}
            </div>

            <div className="mt-8 flex flex-col items-center gap-4">
                <p className="text-xl text-gray-400 font-mono">
                    SYSTEM STATUS: <span className="text-green-400">ONLINE</span>
                </p>

                {/* Contribution Link */}
                <Link
                    href="https://github.com/Guatapickl/gay-i-concierge/tree/main/components/robots"
                    target="_blank"
                    className="flex items-center gap-2 px-4 py-2 rounded-full bg-white/5 hover:bg-white/10 text-sm text-gray-400 transition-colors border border-white/10"
                >
                    <Github size={16} />
                    <span>Add your own robot</span>
                </Link>
            </div>
        </div>
    );
}
